### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Exoduz10** [wojciechteclaw/GeometryJoin#1]
Po ściągnięciu i uruchomieniu, skrypt nie działa. Jakieś zmiany trzeba w nim wprowadzać, aby był do użycia?
![obraz](https://user-images.githubusercontent.com/68873399/88586342-90007200-d054-11ea-8cf5-7ba5d4b0b8f1.png)

**Comment by wojciechteclaw** [comment]
Skrypt jest przygotowany dla angielskiej wersji revit.

Zmień mapowanie:
mapType = {
    "Walls" : ("Floors", "Structural Columns"),
    "Floors" : ("Strcutral Framing", "Structural Columns"),
    "Structural Framing" : ("Walls"),
    "Structural Columns" : ("Structural Framing", "Floors", "Structural Foundations"),
    "Structural Foundations" : ("Floors", "Walls")
    }

Zamiast Floors wpisz polski odpowiednik itp. W wolnej chwili zrobię to na id poszczególnych kategorii aby wszystko chodziło niezależnie od wersji językowej.
